FROM python:3

RUN pip install grpcio protobuf pycodestyle

WORKDIR /kvclient

code:
    COPY client.py .
    COPY ../proto+proto-py/py-pb/*.py .

lint:
    FROM +code
    RUN pycodestyle client.py

kvclient-docker:
    FROM +code
    SAVE IMAGE as python-kvclient:latest

all:
    BUILD +lint
    BUILD +kvclient-docker
